[theme]
base = "light"
primaryColor = "#006BDE"
backgroundColor = "#F2F2F7"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#000000"
font = "sans serif"

[client]
toolbarMode = "minimal"
showErrorDetails = false

[browser]
gatherUsageStats = false

[server]
headless = true
runOnSave = false
